gems: [jekyll-paginate]
encoding: UTF-8
title: Datasnail 蜗牛笔记
name: DataSnail's BLOG
motto: Talk is cheap, show me the code!
email: datasnail@163.com
github: datasnail.github.com
description: Focus on social computing, machine learning and data mining.
paginate: 10
paginate_path: "page:num"
markdown: kramdown
banner: 在抽象的意义下，一切科学都是数学。
highlighter: rouge
